### ISSUE TITLE
Code reduction or basic true RMS code

### ISSUE THREAD

**Issue by classic-audio** [MartinStokroos/TrueRMS#1]
I have downloaded your library to day because I was looking for a trueRMS measuring with Arduino (UNO - NANO).
I would like to have a code which could measure sine signals and white noise signals.

**Your library works really fine.**
_Thank you very much for sharing this great solution._

My question:
Would it be possible to reduce the files or perhaps you would share the basic trueRMS code for the measuring only trueRMS voltage.
I would also like to implement the code in small application with e.g. ATtine 85 which I use for small trueRMS monitors in my test equipment.

My applications are audio test equipment and right now I am working on a test interface for power audio amplifiers.
The equipment is for my own use only - no commercial issues.

**Comment by MartinStokroos** [comment]
Hi classic-audio,
Thanks for using my library and for your commendation. I developed this library for use in power converter applications.
To answer your question: In fact, if you don't use the average or power classes, the code will not be compiled into your project. For your own project you could easily strip out the average and power classes and only keep Rms::begin, Rms::update and Rms::publish.
