### ISSUE TITLE
Frequency range

### ISSUE THREAD

**Issue by classic-audio** [MartinStokroos/TrueRMS#2]
By using the TrueRMS lib. I have some problems measuring frequences above 4kHz.
This is a problem for me.
I am using the TrueRMS measuring  sine signals on power audio amplifiers.
What can I do to be able to measure up to at least 20kHz?

**Comment by MartinStokroos** [comment]
Hi classic-audio,
With the base-line restoring option switched off, the Rms update routine takes about 30 micro-seconds at maximum on the Arduino-UNO.  Assume we execute the update function each 40us (at the  sample frequency of 25kHz). For accurate measurements multiple samples per period are necessary.  So indeed we end up in a few kHz maximum. I always check the duration of my functions and code with an oscilloscope by toggling I/O-pins to prevent from overruns.
This library was developed with the purpose of power converter systems working at the grid frequency. If you want to use it for audio, I would recommend you to:

- not to use the analogRead function of the Arduino library. It consumes too much processing time.
- step over to a 32-bit MCU, like the STM32F3/F4 series or Arduino DUE
- use a different way to calculate the RMS value, for example by using random sampling. This method is described in the article series about AVR Sofware Defined Radio in Elektor Magazine by Martin Ossmann (https://www.elektormagazine.com/tags/avr-software-defined-radio-article-series).

Best Regards,
Martin
