### ISSUE TITLE
current sensor/voltage sensor

### ISSUE THREAD

**Issue by kikiloaw** [MartinStokroos/TrueRMS#3]
hello i am trying to use this library for different sensor
for example acs712 30 amps
having offset of:  2.5v
sensitivity: 0.066v/A
so full 30 amps is = 30 * 0.066 = 1.98v 
offset + fullvoltageReading = 2.5volts + 1.98volts = 4.48volts

I also using just voltage devider for voltage sensing

how do i use this library? i am trying to change the sensor in the grid inverter in your repo since 
the sensor that used their is not available here in hte philippines. also when i try to find the sensor online its very expensive. the sensor price is about 22 dollars where this money for me. but that price is just for one piece only. in your schematic there are 4 over all.

**Comment by MartinStokroos** [comment]
Hello,
You could use any sensor you like as long its output voltage is compliant with the Arduino ADC-input. The specified nominal current of current sensors/transducers is usually the RMS current. There is 2.5V amplitude range available for the ac-component of the sensor output. If I don't make a mistake:
The max measurable rms current is: 2.5/(0.066*sqrt(2)) = 26.78A

outputMeas.begin(currRange, voltRange, RMSWINDOW, ADC_10BIT, BLR_ON, CNT_SCAN);

=> currRange = 5/0.066 = 75.76A
It is recommended to calibrate the scale by using a multi-meter.

**Comment by kikiloaw** [comment]
So does it mean that this library is just a range of measure per adc.  I get it now. Thank you very much. I will update soon, currently designing pcb layout at easy eada
