### ISSUE TITLE
how to measure dc voltage

### ISSUE THREAD

**Issue by fireflies07** [MartinStokroos/TrueRMS#4]
Hi ! thanks for your share the code for measuring the RMS. it good but i got 1 problem when i try with the DC input. the RMS of the DC should be equal to the DC volt input. but the result is showing 0. so i want to ask about the. is have problem or something wrong ! thanks for support !

**Comment by MartinStokroos** [comment]
Dear user of TrueRMS,

In the first place, use with BLR_OFF. To measure DC(+AC) with Rms, do not subtract 512 from the ADC value. This is for AC voltages biased on 2.5V DC to measure AC only.
Better use Average to measure DC or don't use this lib at all and directly read from the ADC.

I hope this will solve your problem.
