### ISSUE TITLE
Using a different ADC reference seems to mess the calculations

### ISSUE THREAD

**Issue by paulvee** [MartinStokroos/TrueRMS#5]
Hi Martin,

First of all thank you for this contribution, it's the best I've found so far.

I have a question regarding the ADC reference voltage used for the Arduino Nano.
When I use the library with the standard Vref setting of using VCC, and I plug-in the actually measured voltage into VoltRange, everything is fine and the RMS result match that of my True RMS DMM and my DSO for sine and other waveforms. I'm not sure I'm using VoltRange in the intended way because I am getting strange output values when I tell the Nano to use the internal reference, and use the actually measured reference voltage for the VoltRange. The results are less then 50% of the VCC setting, so that does not make sense to me.

I don't see where in your code you take the different reference voltage into account.

Any hints on what to do?

Many thanks,
Paul

**Comment by MartinStokroos** [comment]
Dear Paul,

Thank you for making use of my TrueRMS code.
I searched out that the Arduino nano is ATmega328 based and supplied from 5V. By selecting the internal reference, the reference voltage is set to 1.1V. See: https://www.arduino.cc/reference/en/language/functions/analog-io/analogreference/
This means that the DC-bias at the ADC input should be designed to be: 1.1/2 = 0.55V and the AC voltage amplitude to the ADC input should be limited to max 0.55V. In principle, nothing has to change from the library when selecting a different ADC reference voltage. The mid range code value of the ADC remains the same (512). 'VoltRange' should be the peak-to-peak voltage that corresponds to the 0..1.1V ADC input voltage range. I hope this will explain your problem with the readout.

Best regards,
Martin
